# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_rating', models.CharField(max_length=200)),
                ('movie_rating_count', models.IntegerField(default=0)),
                ('movie_year', models.CharField(max_length=200)),
                ('movie_image', models.CharField(max_length=200)),
                ('movie_summary', models.TextField()),
                ('movie_link', models.CharField(max_length=200)),
                ('movie_count', models.IntegerField(default=0)),
            ],
        ),
    ]
